# This is a basic workflow to help you get started with Actions

name: codecov

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: pester
        run: |
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -RequiredVersion 5.0.4 -Force;
          Invoke-Pester -Path "tests" -CodeCoverage "civoShell/civoShell.psm1" -CodeCoverageOutputFileFormat "JaCoCo";
        shell: pwsh
      
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          name: civoShell
          token: ${{ secrets.CODECOV }}
          # Path to coverage file to upload
          file: coverage.xml
